# Generated by Django 4.2.7 on 2023-11-18 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('signin', 'Sign in'), ('logout', 'Sign out'), ('applied', 'Applied'), ('postJob', 'Posted Job'), ('updatePost', 'Update Post'), ('updateProfile', 'Update Profile')], max_length=14)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.user')),
            ],
        ),
    ]
