# Generated by Django 4.2.7 on 2023-11-20 21:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='apartment_no',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='person',
            name='street_address',
        ),
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='contact',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('FB', 'Facebook'), ('IG', 'Instagram'), ('GM', 'Gmail'), ('LI', 'LinkedIn')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('PE', 'Primary Education'), ('LSE', 'Junior High School'), ('USE', 'Senior High School'), ('UG', 'College'), ('PG', 'Master'), ('DC', 'PhD')], max_length=4)),
                ('school_name', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.user')),
            ],
        ),
    ]
