# Generated by Django 4.2.7 on 2023-11-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_remove_user_role'),
        ('accountapp', '0003_remove_person_apartment_no_remove_person_city_and_more'),
    ]

    operations = [
    ]
