# Generated by Django 4.2.7 on 2023-11-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_merge_20231122_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_summary',
            field=models.TextField(default=''),
        ),
    ]
