# Generated by Django 4.2.7 on 2023-11-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_user_profile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='course',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='education',
            name='finished_year',
            field=models.CharField(default='', max_length=12),
        ),
    ]
