# Generated by Django 4.2.7 on 2023-11-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0006_education_course_education_finished_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='finished_year',
        ),
        migrations.AddField(
            model_name='education',
            name='ended_year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AddField(
            model_name='education',
            name='started_year',
            field=models.IntegerField(default=2020),
        ),
    ]
