# Generated by Django 4.2.7 on 2023-11-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0007_remove_education_finished_year_education_ended_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ended_year',
            field=models.CharField(default=2021, max_length=5),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_year',
            field=models.CharField(default='2020', max_length=5),
        ),
    ]
