# Generated by Django 4.2.7 on 2023-11-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0008_alter_education_ended_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ended_year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_year',
            field=models.IntegerField(default=2020),
        ),
    ]
