# Generated by Django 4.2.7 on 2023-11-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0009_alter_education_ended_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='education_level',
            field=models.CharField(choices=[('PE', 'Primary Education'), ('HS', 'High School'), ('UG', 'College'), ('PG', 'Master'), ('DC', 'PhD')], max_length=4),
        ),
    ]
