# Generated by Django 4.2.7 on 2023-11-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0014_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(default='', max_length=12),
        ),
    ]
