# Generated by Django 4.2.7 on 2023-12-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0015_user_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
