# Generated by Django 4.2.7 on 2023-12-06 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0016_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='notification',
            field=models.CharField(choices=[('Applicant', 'New Applicant Applied to your post'), ('MatchSkill', 'Job matches your skill')], default='', max_length=11),
        ),
        migrations.AddField(
            model_name='alerts',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='alerts',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
