# Generated by Django 4.2.7 on 2023-12-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0017_alerts_notification_alerts_status_alerts_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='action_user',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='alerts',
            name='application_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alerts',
            name='is_read',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], default='', max_length=7),
        ),
    ]
