# Generated by Django 4.2.7 on 2023-12-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0018_alerts_action_user_alerts_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
