# Generated by Django 4.2.7 on 2023-12-09 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0007_alter_job_date_posted'),
        ('accountapp', '0019_user_is_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='job',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsapp.job'),
        ),
    ]
