# Generated by Django 4.2.7 on 2023-12-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0020_alerts_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='notification',
            field=models.CharField(choices=[('Applicant', 'New Applicant Applied to your post'), ('MatchSkill', 'Job matches your skill'), ('ApplicationResult', 'Application Result')], default='', max_length=18),
        ),
    ]
