# Generated by Django 4.2.7 on 2023-12-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0021_alter_alerts_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='message',
            field=models.CharField(default='', max_length=220),
        ),
    ]
