# Generated by Django 4.2.7 on 2023-11-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0003_workexperience_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
