# Generated by Django 4.2.7 on 2023-12-02 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0005_job_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 22, 10, 18, 621236)),
        ),
    ]
