# Generated by Django 4.2.7 on 2023-12-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0008_company_city_company_country_company_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/company/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/company/'),
        ),
    ]
