# Generated by Django 4.2.7 on 2023-12-08 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0009_alter_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 25, 18, 175153, tzinfo=datetime.timezone.utc)),
        ),
    ]
