# Generated by Django 4.2.7 on 2023-12-08 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0010_alter_job_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 16, 32, 9, 951607, tzinfo=datetime.timezone.utc)),
        ),
    ]
