# Generated by Django 4.2.7 on 2023-12-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0008_company_city_company_country_company_cover_photo_and_more'),
        ('jobsapp', '0014_jobapplicant'),
    ]

    operations = [
    ]
