# Generated by Django 4.2.7 on 2023-12-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0015_merge_20231209_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
    ]
