# Generated by Django 4.2.7 on 2023-12-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0016_alter_job_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
    ]
