# Generated by Django 4.2.7 on 2023-12-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0015_merge_20231209_2252'),
        ('jobsapp', '0018_alter_job_company'),
    ]

    operations = [
    ]
