# Generated by Django 4.2.7 on 2023-12-10 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0009_alter_company_cover_photo_alter_company_logo'),
        ('jobsapp', '0015_merge_20231209_2357'),
        ('jobsapp', '0019_merge_0015_merge_20231209_2252_0018_alter_job_company'),
    ]

    operations = [
    ]
