# Generated by Django 4.2.7 on 2023-12-10 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0015_merge_20231209_2357'),
        ('jobsapp', '0020_merge_20231210_1129'),
    ]

    operations = [
    ]
