# Generated by Django 4.2.7 on 2023-12-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0020_merge_20231210_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='position',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='job_summary',
            field=models.TextField(default=''),
        ),
    ]
