# Generated by Django 4.2.7 on 2023-12-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0020_merge_20231210_1600'),
        ('jobsapp', '0021_merge_20231210_1153'),
        ('jobsapp', '0021_remove_workexperience_position_and_more'),
    ]

    operations = [
    ]
