# Generated by Django 4.2.7 on 2023-12-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0022_merge_20231210_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
