# Generated by Django 4.2.7 on 2023-12-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0022_merge_20231210_1851'),
        ('jobsapp', '0022_merge_20231210_1857'),
        ('jobsapp', '0023_alter_jobapplicant_status'),
    ]

    operations = [
    ]
