# Generated by Django 4.2.7 on 2023-12-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0022_merge_20231210_1857'),
        ('jobsapp', '0024_merge_20231211_1227'),
    ]

    operations = [
    ]
