# Generated by Django 4.2.7 on 2023-12-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0024_merge_20231211_1227'),
        ('jobsapp', '0024_merge_20231211_1504'),
        ('jobsapp', '0024_merge_20231211_1556'),
    ]

    operations = [
    ]
