# Generated by Django 4.2.7 on 2023-12-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0025_merge_20231211_1648'),
        ('jobsapp', '0025_merge_20231211_1657'),
    ]

    operations = [
    ]
