# Generated by Django 4.2.7 on 2023-12-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0022_merge_20231211_1410'),
        ('jobsapp', '0026_merge_20231211_1815'),
    ]

    operations = [
    ]
