# Generated by Django 4.2.7 on 2023-12-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0027_company_email_address'),
        ('jobsapp', '0027_merge_20231212_1730'),
    ]

    operations = [
    ]
